//
//  MotionStudioEditorRouter.swift
//  MotionStudioApp
//
//  Opens editor scenes and reuses an existing window for the same project URL.
//

import UIKit

@MainActor
enum MotionStudioEditorRouter {
    private static var editorSceneDidConnectObserver: NSObjectProtocol?

    static func isMotionProjectURL(_ url: URL) -> Bool {
        url.pathExtension.lowercased() == AutoGenerated.projectDocumentExtension.lowercased()
    }

    static func editorSession(for projectURL: URL) -> UISceneSession? {
        let target = projectURL.standardizedFileURL
        for case let windowScene as UIWindowScene in UIApplication.shared.connectedScenes {
            guard let openURL = openProjectURL(in: windowScene)?.standardizedFileURL,
                  openURL == target
            else {
                continue
            }
            return windowScene.session
        }
        return nil
    }

    static func activate(activity: NSUserActivity, closeLauncher: Bool = true) {
        if let request = MotionStudioSceneActivity.request(from: activity),
           case let .openProject(url) = request,
           let existingSession = editorSession(for: url)
        {
            UIApplication.shared.requestSceneSessionActivation(existingSession,
                                                               userActivity: nil,
                                                               options: nil)
            if closeLauncher {
                closeLauncherScenes()
            }
            return
        }

        if closeLauncher {
            observeEditorConnectThenCloseLaunchers()
        }
        UIApplication.shared.requestSceneSessionActivation(nil,
                                                           userActivity: activity,
                                                           options: nil)
        { error in
            Task { @MainActor in
                stopWaitingForEditorScene()
                NSLog("MotionStudio: failed to activate editor scene: %@", error.localizedDescription)
            }
        }
    }

    static func openProjectURLs(_ urls: [URL]) {
        for url in urls where isMotionProjectURL(url) {
            openProject(at: url)
        }
    }

    static func openProject(at url: URL) {
        if let existingSession = editorSession(for: url) {
            UIApplication.shared.requestSceneSessionActivation(existingSession,
                                                               userActivity: nil,
                                                               options: nil)
            closeLauncherScenes()
            return
        }

        activate(activity: MotionStudioSceneActivity.openProjectActivity(url: url),
                 closeLauncher: true)
    }

    /// If the system already created a scene for a URL that is open elsewhere, activate the
    /// existing editor and discard the duplicate session.
    @discardableResult
    static func discardDuplicateEditorSessionIfNeeded(_ session: UISceneSession, projectURL: URL) -> Bool {
        guard let existingSession = editorSession(for: projectURL),
              existingSession != session
        else {
            return false
        }

        UIApplication.shared.requestSceneSessionActivation(existingSession,
                                                           userActivity: nil,
                                                           options: nil)
        UIApplication.shared.requestSceneSessionDestruction(session, options: nil)
        return true
    }

    static func closeLauncherScenes() {
        stopWaitingForEditorScene()
        for case let windowScene as UIWindowScene in UIApplication.shared.connectedScenes where isLauncherScene(windowScene) {
            UIApplication.shared.requestSceneSessionDestruction(windowScene.session, options: nil)
        }
    }

    private static func openProjectURL(in windowScene: UIWindowScene) -> URL? {
        if let sceneDelegate = windowScene.delegate as? SceneDelegate {
            return sceneDelegate.openProjectURL
        }
        return nil
    }

    private static func isLauncherScene(_ windowScene: UIWindowScene) -> Bool {
        guard let root = windowScene.windows.first(where: \.isKeyWindow)?.rootViewController
            ?? windowScene.windows.first?.rootViewController
        else {
            return false
        }
        if let navigation = root as? UINavigationController {
            return navigation.viewControllers.first is ProjectListViewController
        }
        return root is ProjectListViewController
    }

    private static func observeEditorConnectThenCloseLaunchers() {
        stopWaitingForEditorScene()
        editorSceneDidConnectObserver = NotificationCenter.default.addObserver(forName: .motionStudioEditorSceneDidConnect,
                                                                               object: nil,
                                                                               queue: .main)
        { _ in
            Task { @MainActor in
                closeLauncherScenes()
            }
        }
    }

    private static func stopWaitingForEditorScene() {
        if let editorSceneDidConnectObserver {
            NotificationCenter.default.removeObserver(editorSceneDidConnectObserver)
            self.editorSceneDidConnectObserver = nil
        }
    }
}
