//
//  MotionProjectDocument.swift
//  MotionStudioApp
//
//  UIDocument wrapper used by the UIKit editor flow. The existing SwiftUI
//  MotionDocument stays unchanged and remains the model document for panels.
//

import UIKit
import UniformTypeIdentifiers

final class MotionProjectDocument: UIDocument {
    private enum Package {
        static let documentFilename = "document.json"
        static let assetsDirectoryName = "assets"
    }

    private(set) var modelDocument: MotionDocument
    private(set) var saveURL: URL
    private(set) var isTemporaryDraft: Bool

    var core: MotionDocumentCore {
        modelDocument.core
    }

    init(fileURL: URL, modelDocument: MotionDocument = MotionDocument(), isTemporaryDraft: Bool = false) {
        self.modelDocument = modelDocument
        saveURL = fileURL
        self.isTemporaryDraft = isTemporaryDraft
        super.init(fileURL: fileURL)
    }

    static func makeTemporaryDraft() -> MotionProjectDocument {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent("MotionStudioDrafts", isDirectory: true)
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let url = directory.appendingPathComponent(UUID().uuidString).appendingPathExtension(AutoGenerated.projectDocumentExtension)
        return MotionProjectDocument(fileURL: url, isTemporaryDraft: true)
    }

    override func contents(forType typeName: String) throws -> Any {
        try packageFileWrapper()
    }

    override func load(fromContents contents: Any, ofType typeName: String?) throws {
        if let data = contents as? Data {
            modelDocument = try MotionDocument(data: data)
            return
        }

        guard let fileWrapper = contents as? FileWrapper else {
            throw CocoaError(.fileReadCorruptFile)
        }

        if let data = fileWrapper.regularFileContents {
            modelDocument = try MotionDocument(data: data)
            return
        }

        guard let data = fileWrapper.fileWrappers?[Package.documentFilename]?.regularFileContents else {
            throw CocoaError(.fileReadCorruptFile)
        }
        modelDocument = try MotionDocument(data: data)
    }

    func snapshotData() throws -> Data {
        try modelDocument.snapshot(contentType: .motionProjectDocument)
    }

    func packageFileWrapper() throws -> FileWrapper {
        let documentData = try snapshotData()
        let root = FileWrapper(directoryWithFileWrappers: [:])
        root.preferredFilename = saveURL.lastPathComponent
        root.addRegularFile(withContents: documentData, preferredFilename: Package.documentFilename)

        let assets = FileWrapper(directoryWithFileWrappers: [:])
        assets.preferredFilename = Package.assetsDirectoryName
        root.addFileWrapper(assets)
        return root
    }

    func markEdited() {
        updateChangeCount(.done)
    }

    func markSaved(to url: URL) {
        saveURL = url
        isTemporaryDraft = false
        updateChangeCount(.cleared)
    }
}
