//
//  MotionProjectDocument.swift
//  MotionStudioApp
//
//  UIDocument wrapper used by the UIKit editor flow. The existing SwiftUI
//  MotionProjectState remains the model state for panels.
//

import UIKit
import UniformTypeIdentifiers

final class MotionProjectDocument: UIDocument {
    private enum Package {
        static let documentFilename = "document.json"
        static let shaderFilename = "shader.json"
        static let assetsDirectoryName = "assets"
    }

    private enum Trash {
        static let directoryName = "ProjectAssetTrash"
    }

    private(set) var modelDocument: MotionProjectState
    private(set) var saveURL: URL
    private(set) var isTemporaryDraft: Bool
    var onSaveStateChanged: (@MainActor @Sendable () -> Void)?

    var core: MotionDocumentCore {
        modelDocument.core
    }

    init(fileURL: URL, modelDocument: MotionProjectState = MotionProjectState(), isTemporaryDraft: Bool = false) {
        self.modelDocument = modelDocument
        saveURL = fileURL
        self.isTemporaryDraft = isTemporaryDraft
        super.init(fileURL: fileURL)
        syncProjectRoot()
    }

    static func makeTemporaryDraft() -> MotionProjectDocument {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent("MotionStudioDrafts", isDirectory: true)
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let url = directory.appendingPathComponent(UUID().uuidString).appendingPathExtension(AutoGenerated.projectDocumentExtension)
        let document = MotionProjectDocument(fileURL: url, isTemporaryDraft: true)
        try? FileManager.default.createDirectory(at: url.appendingPathComponent(Package.assetsDirectoryName), withIntermediateDirectories: true)
        document.syncProjectRoot()
        return document
    }

    override func contents(forType _: String) throws -> Any {
        try packageFileWrapper()
    }

    override func load(fromContents contents: Any, ofType _: String?) throws {
        if let data = contents as? Data {
            // Flat document.json only (no shader.json) → empty shader library.
            modelDocument = try MotionProjectState(documentJSON: data, shadersJSON: nil)
            syncProjectRoot()
            return
        }

        guard let fileWrapper = contents as? FileWrapper else {
            throw CocoaError(.fileReadCorruptFile)
        }

        // document.json + shader.json are merged in one Core load before UI sees the model.
        let documentData = try documentData(from: fileWrapper)
        let shadersData = shaderData(from: fileWrapper)
        modelDocument = try MotionProjectState(documentJSON: documentData, shadersJSON: shadersData)
        try materializeAssets(from: fileWrapper)
        syncProjectRoot()
    }

    override func updateChangeCount(withToken changeCountToken: Any, for saveOperation: UIDocument.SaveOperation) {
        super.updateChangeCount(withToken: changeCountToken, for: saveOperation)
        let onSaveStateChanged = onSaveStateChanged
        Task { @MainActor in
            onSaveStateChanged?()
        }
    }

    func snapshotData() throws -> Data {
        try modelDocument.snapshot(contentType: .motionProjectDocument)
    }

    func packageFileWrapper() throws -> FileWrapper {
        syncProjectRoot()
        let documentData = try snapshotData()
        let shadersData = try core.serializeShaders()
        let root = FileWrapper(directoryWithFileWrappers: [:])
        root.preferredFilename = saveURL.lastPathComponent
        root.addRegularFile(withContents: documentData, preferredFilename: Package.documentFilename)
        root.addRegularFile(withContents: shadersData, preferredFilename: Package.shaderFilename)

        let assets = FileWrapper(directoryWithFileWrappers: [:])
        assets.preferredFilename = Package.assetsDirectoryName
        try addAssetFiles(to: assets)
        root.addFileWrapper(assets)
        return root
    }

    func markEdited() {
        updateChangeCount(.done)
    }

    func markSaved(to url: URL) {
        saveURL = url
        isTemporaryDraft = false
        syncProjectRoot()
    }

    func syncProjectRoot() {
        core.setProjectRoot(saveURL.path(percentEncoded: false))
        core.setAssetTrashRoot(Self.assetTrashRootURL.path(percentEncoded: false))
    }

    static func clearAssetTrashRootAsync() {
        let trashRootURL = assetTrashRootURL
        Task.detached(priority: .utility) {
            let fileManager = FileManager.default
            try? fileManager.removeItem(at: trashRootURL)
            try? fileManager.createDirectory(at: trashRootURL, withIntermediateDirectories: true)
        }
    }

    private static var assetTrashRootURL: URL {
        FileManager.default.temporaryDirectory
            .appendingPathComponent(Trash.directoryName, isDirectory: true)
    }

    private func addAssetFiles(to assetsWrapper: FileWrapper) throws {
        let assetsDirectory = saveURL.appendingPathComponent(Package.assetsDirectoryName, isDirectory: true)
        guard FileManager.default.fileExists(atPath: assetsDirectory.path(percentEncoded: false)) else {
            return
        }
        let fileURLs = try FileManager.default.contentsOfDirectory(
            at: assetsDirectory,
            includingPropertiesForKeys: [.isRegularFileKey],
            options: [.skipsHiddenFiles],
        )
        for fileURL in fileURLs {
            let values = try fileURL.resourceValues(forKeys: [.isRegularFileKey])
            guard values.isRegularFile == true else {
                continue
            }
            let data = try Data(contentsOf: fileURL)
            assetsWrapper.addRegularFile(withContents: data, preferredFilename: fileURL.lastPathComponent)
        }
    }

    private func materializeAssets(from fileWrapper: FileWrapper) throws {
        guard fileWrapper.isDirectory,
              let assetsWrapper = fileWrapper.fileWrappers?[Package.assetsDirectoryName],
              assetsWrapper.isDirectory,
              let children = assetsWrapper.fileWrappers
        else {
            try FileManager.default.createDirectory(
                at: saveURL.appendingPathComponent(Package.assetsDirectoryName),
                withIntermediateDirectories: true,
            )
            return
        }

        let assetsDirectory = saveURL.appendingPathComponent(Package.assetsDirectoryName, isDirectory: true)
        try FileManager.default.createDirectory(at: assetsDirectory, withIntermediateDirectories: true)
        for (name, child) in children {
            guard child.isRegularFile, let data = child.regularFileContents else {
                continue
            }
            try data.write(to: assetsDirectory.appendingPathComponent(name), options: .atomic)
        }
    }

    private func documentData(from fileWrapper: FileWrapper) throws -> Data {
        if fileWrapper.isRegularFile,
           let data = fileWrapper.regularFileContents
        {
            return data
        }

        if fileWrapper.isDirectory,
           let documentWrapper = fileWrapper.fileWrappers?[Package.documentFilename],
           documentWrapper.isRegularFile,
           let data = documentWrapper.regularFileContents
        {
            return data
        }

        let packageURL = fileURL.appendingPathComponent(Package.documentFilename)
        if FileManager.default.fileExists(atPath: packageURL.path(percentEncoded: false)) {
            return try Data(contentsOf: packageURL)
        }

        throw CocoaError(.fileReadCorruptFile)
    }

    /// Optional shader.json beside document.json. Missing file → nil (empty library on load).
    private func shaderData(from fileWrapper: FileWrapper) -> Data? {
        if fileWrapper.isDirectory,
           let shaderWrapper = fileWrapper.fileWrappers?[Package.shaderFilename],
           shaderWrapper.isRegularFile,
           let data = shaderWrapper.regularFileContents
        {
            return data
        }

        let packageURL = fileURL.appendingPathComponent(Package.shaderFilename)
        if FileManager.default.fileExists(atPath: packageURL.path(percentEncoded: false)) {
            return try? Data(contentsOf: packageURL)
        }
        return nil
    }
}
