//
//  MotionDocument.swift
//  MotionStudioApp
//
//  ReferenceFileDocument backed by the C++ core.
//

import Combine
import SwiftUI
import UniformTypeIdentifiers

extension UTType {
    nonisolated static var motionProjectDocument: UTType {
        UTType(exportedAs: AutoGenerated.projectDocumentIdentifier)
    }
}

/// Document type for DocumentGroup. Reference semantics match the C++ core:
/// the model is never copied on edit, and undo is handled by the core's
/// command stack (registered with the system UndoManager by the editor UI).
///
/// SwiftUI calls the protocol methods from non-main isolation domains (per
/// the ReferenceFileDocument contract, serialization must not run on the
/// MainActor), so the conformances are nonisolated. Concurrent access between
/// background snapshots and main-actor edits is serialized by the bridge's
/// document mutex.
@MainActor
final class MotionDocument: ReferenceFileDocument {
    nonisolated static var readableContentTypes: [UTType] {
        [.motionProjectDocument]
    }

    // Explicit nonisolated witness: with MainActor default isolation, the
    // synthesized ObservableObject witness would be main-actor isolated and
    // cannot satisfy the protocol's nonisolated requirement.
    private nonisolated(unsafe) let publisher = ObservableObjectPublisher()
    nonisolated var objectWillChange: ObservableObjectPublisher {
        publisher
    }

    let core: MotionDocumentCore

    nonisolated init() {
        core = MotionDocumentCore()
        bindChangeTracking()
    }

    nonisolated init(data: Data) throws {
        core = try Self.makeCore(data: data)
        bindChangeTracking()
    }

    nonisolated init(configuration: ReadConfiguration) throws {
        guard let data = configuration.file.regularFileContents else {
            throw CocoaError(.fileReadCorruptFile)
        }
        core = try Self.makeCore(data: data)
        bindChangeTracking()
    }

    private nonisolated static func makeCore(data: Data) throws -> MotionDocumentCore {
        try MotionDocumentCore(json: data)
    }

    /// Forwards every core mutation to objectWillChange so the document system
    /// marks the document edited (title-bar dot, close prompt, Save enabling).
    /// nonisolated so it can run from the nonisolated inits; the callback is
    /// typed as @MainActor and only touches the nonisolated publisher.
    private nonisolated func bindChangeTracking() {
        core.onDidChange = { [weak self] in
            self?.publisher.send()
        }
    }

    /// Captures the snapshot off the main actor (bridge provides the lock).
    nonisolated func snapshot(contentType _: UTType) throws -> Data {
        try core.serialize()
    }

    /// Runs in the background with the snapshot taken above.
    nonisolated func fileWrapper(snapshot: Data, configuration _: WriteConfiguration) throws -> FileWrapper {
        FileWrapper(regularFileWithContents: snapshot)
    }
}
