//
//  MotionDocument.swift
//  MotionStudioApp
//
//  ReferenceFileDocument backed by the C++ core.
//

import Combine
import SwiftUI
import UniformTypeIdentifiers

extension UTType {
    static let motionStudioDocument = UTType(exportedAs: AutoGenerated.documentIdentifier)
}

/// Document type for DocumentGroup. Reference semantics match the C++ core:
/// the model is never copied on edit, and undo is handled by the core's
/// command stack (registered with the system UndoManager by the editor UI).
///
/// SwiftUI calls the protocol methods from non-main isolation domains (per
/// the ReferenceFileDocument contract, serialization must not run on the
/// MainActor), so the conformances are nonisolated. Concurrent access between
/// background snapshots and main-actor edits is serialized by the bridge's
/// document mutex.
@MainActor
final class MotionDocument: ReferenceFileDocument {
    nonisolated static var readableContentTypes: [UTType] {
        [.motionStudioDocument]
    }

    // Explicit nonisolated witness: with MainActor default isolation, the
    // synthesized ObservableObject witness would be main-actor isolated and
    // cannot satisfy the protocol's nonisolated requirement.
    private nonisolated let publisher = ObservableObjectPublisher()
    nonisolated var objectWillChange: ObservableObjectPublisher {
        publisher
    }

    let core: MotionDocumentCore

    nonisolated init() {
        core = MotionDocumentCore()
    }

    nonisolated init(configuration: ReadConfiguration) throws {
        guard let data = configuration.file.regularFileContents else {
            throw CocoaError(.fileReadCorruptFile)
        }
        core = try MotionDocumentCore(json: data)
    }

    /// Captures the snapshot off the main actor (bridge provides the lock).
    nonisolated func snapshot(contentType _: UTType) throws -> Data {
        try core.serialize()
    }

    /// Runs in the background with the snapshot taken above.
    nonisolated func fileWrapper(snapshot: Data,
                                 configuration _: WriteConfiguration) throws -> FileWrapper
    {
        FileWrapper(regularFileWithContents: snapshot)
    }
}
