//
//  MotionProjectState.swift
//  MotionStudioApp
//
//  Minimal observable project state shared by UIKit and hosted SwiftUI panels.
//

import Foundation
import Observation
import UniformTypeIdentifiers

extension UTType {
    nonisolated static var motionProjectDocument: UTType {
        UTType(exportedAs: AutoGenerated.projectDocumentIdentifier)
    }
}

@MainActor
@Observable
final class MotionProjectState {
    let core: MotionDocumentCore

    nonisolated init() {
        core = MotionDocumentCore()
    }

    nonisolated init(data: Data) throws {
        core = try MotionDocumentCore(json: data)
    }

    nonisolated func snapshot(contentType _: UTType) throws -> Data {
        try core.serialize()
    }
}
