//
//  MotionDocument.swift
//  MotionStudioApp
//
//  ReferenceFileDocument backed by the C++ core.
//

import Combine
import SwiftUI
import UniformTypeIdentifiers

extension UTType {
    static let motionStudioDocument = UTType(exportedAs: AutoGenerated.documentIdentifier)
}

/// Document type for DocumentGroup. Reference semantics match the C++ core:
/// the model is never copied on edit, and undo is handled by the core's
/// command stack (registered with the system UndoManager by the editor UI).
///
/// The protocol requirements are nonisolated while the core is MainActor;
/// SwiftUI invokes init/snapshot on the main thread, so the conformances
/// bridge with MainActor.assumeIsolated.
@MainActor
final class MotionDocument: ReferenceFileDocument {
    nonisolated static var readableContentTypes: [UTType] { [.motionStudioDocument] }

    // Explicit nonisolated witness: with MainActor default isolation, the
    // synthesized ObservableObject witness would be main-actor isolated and
    // cannot satisfy the protocol's nonisolated requirement.
    private nonisolated let publisher = ObservableObjectPublisher()
    nonisolated var objectWillChange: ObservableObjectPublisher { publisher }

    let core: MotionDocumentCore

    nonisolated init() {
        core = MotionDocumentCore()
    }

    nonisolated init(configuration: ReadConfiguration) throws {
        guard let data = configuration.file.regularFileContents else {
            throw CocoaError(.fileReadCorruptFile)
        }
        core = try MotionDocumentCore(json: data)
    }

    // Captures the snapshot synchronously on the main thread.
    nonisolated func snapshot(contentType: UTType) throws -> Data {
        try MainActor.assumeIsolated {
            try core.serialize()
        }
    }

    // Runs in the background with the snapshot taken above.
    nonisolated func fileWrapper(snapshot: Data,
                                 configuration: WriteConfiguration) throws -> FileWrapper {
        FileWrapper(regularFileWithContents: snapshot)
    }
}
