//
//  EditorViewController+Saving.swift
//  MotionStudioApp
//
//  UIKit document saving for the editor shell.
//

import UIKit

@MainActor
extension EditorViewController {
    var hasUnsavedChanges: Bool {
        document.isTemporaryDraft || document.hasUnsavedChanges
    }

    func initializeSaveStateIfNeeded() {
        updateSaveButtonState()
    }

    func updateSaveButtonState() {
        saveButton.tintColor = hasUnsavedChanges ? Palette.buttonTint : .secondaryLabel
        saveButton.backgroundColor = hasUnsavedChanges ? Palette.buttonBackground : .clear
        updateDocumentStatusView()
        updateWindowCloseAvailability()
        UIMenuSystem.main.setNeedsRevalidate()
    }

    func updateDocumentStatusView() {
        let projectName = document.saveURL.deletingPathExtension().lastPathComponent
        documentDirtyIndicator.isHidden = !hasUnsavedChanges
        documentStatusLabel.text = hasUnsavedChanges ? "\(projectName) · Modified" : projectName
        documentStatusLabel.textColor = hasUnsavedChanges ? .label : .secondaryLabel
    }

    @objc func saveCurrentDocument() {
        guard !document.isTemporaryDraft else {
            saveDocumentAs()
            return
        }

        saveDocument(to: document.saveURL, operation: .forOverwriting)
    }

    @objc func saveDocumentAs() {
        do {
            let temporaryDocumentURL = try makeSaveAsTemporaryDocument()
            let picker = UIDocumentPickerViewController(forExporting: [temporaryDocumentURL], asCopy: true)
            picker.delegate = self
            picker.shouldShowFileExtensions = true
            present(picker, animated: true)
        } catch {
            presentSaveError(error)
        }
    }

    func saveDocument(to url: URL, operation: UIDocument.SaveOperation,
                      completion: (@MainActor (Bool) -> Void)? = nil)
    {
        let shouldStopAccessing = url.startAccessingSecurityScopedResource()
        document.save(to: url, for: operation) { [weak self] success in
            Task { @MainActor in
                guard let self else {
                    completion?(false)
                    return
                }
                if shouldStopAccessing {
                    url.stopAccessingSecurityScopedResource()
                }
                if success {
                    self.markSaved(at: url)
                } else {
                    self.presentSaveError(CocoaError(.fileWriteUnknown))
                }
                completion?(success)
            }
        }
    }

    func markSaved(at url: URL) {
        document.markSaved(to: url)
        ProjectLibraryStore.remember(url: url)
        title = url.deletingPathExtension().lastPathComponent
        updateSaveButtonState()
    }

    private func makeSaveAsTemporaryDocument() throws -> URL {
        removeSaveAsTemporaryDocument()

        let temporaryDirectoryURL = FileManager.default.temporaryDirectory
            .appendingPathComponent("MotionStudioSaveAs-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: temporaryDirectoryURL, withIntermediateDirectories: true)

        do {
            let projectName = document.isTemporaryDraft
                ? "Untitled"
                : document.saveURL.deletingPathExtension().lastPathComponent
            let temporaryDocumentURL = temporaryDirectoryURL
                .appendingPathComponent(projectName)
                .appendingPathExtension(AutoGenerated.projectDocumentExtension)
            let fileWrapper = try document.packageFileWrapper()
            try fileWrapper.write(to: temporaryDocumentURL, options: .atomic, originalContentsURL: nil)
            saveAsTemporaryDirectoryURL = temporaryDirectoryURL
            return temporaryDocumentURL
        } catch {
            try? FileManager.default.removeItem(at: temporaryDirectoryURL)
            throw error
        }
    }

    private func removeSaveAsTemporaryDocument() {
        guard let saveAsTemporaryDirectoryURL else {
            return
        }
        self.saveAsTemporaryDirectoryURL = nil
        try? FileManager.default.removeItem(at: saveAsTemporaryDirectoryURL)
    }

    private func presentSaveError(_ error: Error) {
        let alert = UIAlertController(title: "Save Failed",
                                      message: error.localizedDescription,
                                      preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default))
        present(alert, animated: true)
    }
}

extension EditorViewController: UIDocumentPickerDelegate {
    func documentPicker(_: UIDocumentPickerViewController, didPickDocumentsAt _: [URL]) {
        removeSaveAsTemporaryDocument()
    }

    func documentPickerWasCancelled(_: UIDocumentPickerViewController) {
        removeSaveAsTemporaryDocument()
    }
}
