//
//  EditorViewController+Saving.swift
//  MotionStudioApp
//
//  UIKit document saving for the editor shell.
//

import UIKit
import UniformTypeIdentifiers

@MainActor
extension EditorViewController {
    var hasUnsavedChanges: Bool {
        document.isTemporaryDraft || document.hasUnsavedChanges
    }

    func initializeSaveStateIfNeeded() {
        updateSaveButtonState()
    }

    func updateSaveButtonState() {
        saveButton.tintColor = hasUnsavedChanges ? Palette.buttonTint : .secondaryLabel
        saveButton.backgroundColor = hasUnsavedChanges ? Palette.buttonBackground : .clear
    }

    @objc func saveCurrentDocument() {
        guard !document.isTemporaryDraft else {
            saveDocumentAs()
            return
        }

        saveDocument(to: document.saveURL, operation: .forOverwriting)
    }

    @objc func saveDocumentAs() {
        do {
            let exportURL = try writeTemporaryExportPackage()
            pendingExportURL = exportURL
            let picker = UIDocumentPickerViewController(forExporting: [exportURL], asCopy: true)
            picker.delegate = self
            present(picker, animated: true)
        } catch {
            presentSaveError(error)
        }
    }

    func saveDocument(to url: URL, operation: UIDocument.SaveOperation) {
        let shouldStopAccessing = url.startAccessingSecurityScopedResource()
        document.save(to: url, for: operation) { [weak self] success in
            guard let self else { return }
            if shouldStopAccessing {
                url.stopAccessingSecurityScopedResource()
            }
            if success {
                self.markSaved(at: url)
            } else {
                self.presentSaveError(CocoaError(.fileWriteUnknown))
            }
        }
    }

    func markSaved(at url: URL) {
        document.markSaved(to: url)
        title = url.deletingPathExtension().lastPathComponent
        updateSaveButtonState()
    }

    private func writeTemporaryExportPackage() throws -> URL {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent("MotionStudioExports", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        let baseName = document.isTemporaryDraft ? "Untitled" : document.saveURL.deletingPathExtension().lastPathComponent
        let url = directory.appendingPathComponent(baseName).appendingPathExtension(AutoGenerated.projectDocumentExtension)
        try? FileManager.default.removeItem(at: url)
        try document.packageFileWrapper().write(to: url, options: .atomic, originalContentsURL: nil)
        return url
    }

    private func presentSaveError(_ error: Error) {
        let alert = UIAlertController(title: "Save Failed",
                                      message: error.localizedDescription,
                                      preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default))
        present(alert, animated: true)
    }
}

extension EditorViewController: UIDocumentPickerDelegate {
    func documentPicker(_ controller: UIDocumentPickerViewController, didPickDocumentsAt urls: [URL]) {
        defer {
            if let pendingExportURL {
                try? FileManager.default.removeItem(at: pendingExportURL)
            }
            pendingExportURL = nil
        }

        guard let savedURL = urls.first else { return }
        markSaved(at: savedURL)
    }

    func documentPickerWasCancelled(_ controller: UIDocumentPickerViewController) {
        if let pendingExportURL {
            self.pendingExportURL = nil
            try? FileManager.default.removeItem(at: pendingExportURL)
        }
    }
}
