//
//  ProjectLibraryStore.swift
//  MotionStudioApp
//
//  Local project library backed by Documents/Projects.
//

import Foundation

struct ProjectLibraryItem {
    let url: URL
    let modifiedAt: Date
}

enum ProjectLibraryStore {
    static func projectURLs() -> [URL] {
        projectItems().map(\.url)
    }

    static func projectItems() -> [ProjectLibraryItem] {
        guard let directory = try? projectsDirectory() else { return [] }
        let keys: Set<URLResourceKey> = [.contentModificationDateKey, .isDirectoryKey]
        let urls = (try? FileManager.default.contentsOfDirectory(at: directory,
                                                                  includingPropertiesForKeys: Array(keys),
                                                                  options: [.skipsHiddenFiles])) ?? []

        return urls.compactMap { url in
            guard url.pathExtension == AutoGenerated.projectDocumentExtension else { return nil }
            let values = try? url.resourceValues(forKeys: keys)
            let isDirectory = values?.isDirectory ?? false
            guard isDirectory else { return nil }
            return ProjectLibraryItem(url: url,
                                      modifiedAt: values?.contentModificationDate ?? .distantPast)
        }
        .sorted { lhs, rhs in
            if lhs.modifiedAt == rhs.modifiedAt {
                return lhs.url.lastPathComponent.localizedStandardCompare(rhs.url.lastPathComponent) == .orderedAscending
            }
            return lhs.modifiedAt > rhs.modifiedAt
        }
    }

    static func remember(url: URL) {
        guard isInProjectLibrary(url) else { return }
    }

    static func remove(url: URL) throws {
        guard isInProjectLibrary(url) else { return }
        try FileManager.default.removeItem(at: url)
    }

    static func rename(url: URL, to name: String) throws -> URL {
        let sourceURL = url.standardizedFileURL
        guard FileManager.default.fileExists(atPath: sourceURL.path(percentEncoded: false)) else {
            throw CocoaError(.fileNoSuchFile)
        }

        guard isInProjectLibrary(sourceURL) else {
            throw CocoaError(.fileNoSuchFile)
        }

        let destinationURL = try projectURL(for: name).standardizedFileURL
        guard destinationURL != sourceURL else {
            return sourceURL
        }

        guard !FileManager.default.fileExists(atPath: destinationURL.path(percentEncoded: false)) else {
            throw CocoaError(.fileWriteFileExists)
        }

        try FileManager.default.moveItem(at: sourceURL, to: destinationURL)
        return destinationURL
    }

    static func makeNewProjectURL() throws -> URL {
        try uniqueProjectURL(baseName: "Untitled")
    }

    static func makeProjectCopyURL(for url: URL) throws -> URL {
        let baseName = url.deletingPathExtension().lastPathComponent
        return try uniqueProjectURL(baseName: "\(baseName) Copy")
    }

    static func importProjectIfNeeded(from sourceURL: URL) throws -> URL {
        if isInProjectLibrary(sourceURL) {
            return sourceURL
        }

        let destinationURL = try uniqueProjectURL(baseName: sourceURL.deletingPathExtension().lastPathComponent)
        try FileManager.default.copyItem(at: sourceURL, to: destinationURL)
        return destinationURL
    }

    static func projectsDirectory() throws -> URL {
        let documents = try FileManager.default.url(for: .documentDirectory,
                                                    in: .userDomainMask,
                                                    appropriateFor: nil,
                                                    create: true)
        let directory = documents.appendingPathComponent("Projects", isDirectory: true)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        return directory
    }

    private static func uniqueProjectURL(baseName: String) throws -> URL {
        let sanitizedBaseName = sanitizedProjectName(baseName)
        let directory = try projectsDirectory()
        let fileExtension = AutoGenerated.projectDocumentExtension
        var candidate = directory.appendingPathComponent(sanitizedBaseName).appendingPathExtension(fileExtension)
        var index = 2

        while FileManager.default.fileExists(atPath: candidate.path(percentEncoded: false)) {
            candidate = directory.appendingPathComponent("\(sanitizedBaseName) \(index)").appendingPathExtension(fileExtension)
            index += 1
        }

        return candidate
    }

    private static func projectURL(for name: String) throws -> URL {
        try projectsDirectory()
            .appendingPathComponent(sanitizedProjectName(name))
            .appendingPathExtension(AutoGenerated.projectDocumentExtension)
    }

    private static func sanitizedProjectName(_ name: String) -> String {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        let nameWithoutExtension = trimmed.hasSuffix(".\(AutoGenerated.projectDocumentExtension)")
            ? String(trimmed.dropLast(AutoGenerated.projectDocumentExtension.count + 1))
            : trimmed
        let invalidCharacters = CharacterSet(charactersIn: "/:")
        let sanitized = nameWithoutExtension.components(separatedBy: invalidCharacters).joined(separator: "-")
        return sanitized.isEmpty ? "Untitled" : sanitized
    }

    private static func isInProjectLibrary(_ url: URL) -> Bool {
        guard let directory = try? projectsDirectory() else { return false }
        let projectPath = normalizedDirectoryPath(url.standardizedFileURL.path(percentEncoded: false))
        let directoryPath = normalizedDirectoryPath(directory.standardizedFileURL.path(percentEncoded: false))
        return projectPath == directoryPath || projectPath.hasPrefix(directoryPath + "/")
    }

    private static func normalizedDirectoryPath(_ path: String) -> String {
        var normalized = path
        while normalized.count > 1, normalized.hasSuffix("/") {
            normalized.removeLast()
        }
        return normalized
    }
}
