macro(add_files_by_extension target_var extensions)
  set(directories ${ARGN})
  if(NOT DEFINED ENV{extensions})
    string(REGEX MATCH "^.*;.*;.*$" IS_LIST_STRING "${extensions}")
    if(NOT IS_LIST_STRING)
      string(REPLACE ";" " " extensions "${extensions}")
      string(REGEX REPLACE "([^\ ]+)" "\\1;" extensions "${extensions}")
    endif()
  endif()

  set(${target_var} "")

  foreach(dir ${directories})
    foreach(ext ${extensions})
      set(glob_pattern "${dir}/*${ext}")
      file(GLOB_RECURSE temp_files ${glob_pattern})
      list(APPEND ${target_var} ${temp_files})
    endforeach()
  endforeach()

  # Sort by directory + stem so peers stay together; headers (.h/.hpp) before
  # same-stem sources (.c/.cc/.cpp/.m/.mm). Plain path sort would put .cpp
  # ahead of .h.
  set(_afe_sortable "")
  foreach(_afe_file IN LISTS ${target_var})
    get_filename_component(_afe_dir "${_afe_file}" DIRECTORY)
    get_filename_component(_afe_stem "${_afe_file}" NAME_WE)
    get_filename_component(_afe_ext "${_afe_file}" EXT)
    set(_afe_rank 1)
    if(_afe_ext STREQUAL ".h" OR _afe_ext STREQUAL ".hpp")
      set(_afe_rank 0)
    endif()
    list(APPEND _afe_sortable "${_afe_dir}/${_afe_stem}|${_afe_rank}|${_afe_file}")
  endforeach()
  list(SORT _afe_sortable COMPARE STRING)
  set(${target_var} "")
  foreach(_afe_entry IN LISTS _afe_sortable)
    string(REGEX REPLACE "^[^|]*\\|[01]\\|" "" _afe_file "${_afe_entry}")
    list(APPEND ${target_var} "${_afe_file}")
  endforeach()
  unset(_afe_sortable)
  unset(_afe_file)
  unset(_afe_dir)
  unset(_afe_stem)
  unset(_afe_ext)
  unset(_afe_rank)
  unset(_afe_entry)
endmacro()

function(make_files_relative OUT_VAR BASE_DIR)
  set(_result)
  foreach(_abs IN LISTS ARGN)
    file(RELATIVE_PATH _rel "${BASE_DIR}" "${_abs}")
    list(APPEND _result "${_rel}")
  endforeach()
  set(${OUT_VAR} "${_result}")
endfunction()

function(add_source_group files base_dir group_prefix)
  foreach(file IN LISTS ${files})
    file(RELATIVE_PATH rel_path "${base_dir}" "${file}")
    get_filename_component(group_path "${rel_path}" DIRECTORY)
    if(group_path STREQUAL "")
      # set(group_path "${group_prefix}")
      source_group("${group_prefix}" FILES "${file}")
    else()
      source_group("${group_prefix}\\${group_path}" FILES "${file}")
    endif()
  endforeach()
endfunction()

function(disable_xcode_target_signing target_name)
  if(CMAKE_GENERATOR MATCHES "Xcode")
    message(STATUS "========= disable xcode target signing for ${target_name} =========")
    set_target_properties(${target_name} PROPERTIES
      XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "-"
      XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED "NO"
    )
  endif()
endfunction()

function(set_xcode_target_tgfx_prebuilt_search_paths target_name)
  if(CMAKE_GENERATOR MATCHES "Xcode")
    message(STATUS "========= configuration tgfx prebuilt search paths for ${target_name} =========")
    message(STATUS "TGFX_PREBUILT_CATALYST_DIR: ${TGFX_PREBUILT_CATALYST_DIR}")
    message(STATUS "TGFX_PREBUILT_IOS_DIR: ${TGFX_PREBUILT_IOS_DIR}")
    message(STATUS "TGFX_PREBUILT_IOSSIM_DIR: ${TGFX_PREBUILT_IOSSIM_DIR}")
    set_target_properties(${target_name} PROPERTIES
      XCODE_ATTRIBUTE_LIBRARY_SEARCH_PATHS[sdk=macosx*] "${TGFX_PREBUILT_CATALYST_DIR}"
      XCODE_ATTRIBUTE_LIBRARY_SEARCH_PATHS[sdk=iphoneos*] "${TGFX_PREBUILT_IOS_DIR}"
      XCODE_ATTRIBUTE_LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*] "${TGFX_PREBUILT_IOSSIM_DIR}"
    )
  endif()
endfunction()
