#pragma once

namespace motion {

// Identifies the concrete command type so mergeWith can type-check the other
// command before downcasting (dynamic_cast is banned by the coding rules).
enum class CommandKind {
    AddLayer,
    RemoveLayer,
    MoveLayer,
    SetParent,
    SetStaticValue,
    AddKeyframe,
    RemoveKeyframe,
    MoveKeyframe,
    SetEasing,
    SetLayerVisible,
    SetLayerLocked,
    SetLayerName,
    SetCompositionBackgroundColor,
    SetCompositionCornerRadius,
    SetCompositionSettings,
    AddLayerStyle,
    RemoveStyle,
    MoveLayerStyle,
    AddLayerEffect,
    RemoveLayerEffect,
    MoveLayerEffect,
    SetLayerEffectEnabled,
    AddLayerFx,
    RemoveLayerFx,
    MoveLayerFx,
    SetLayerFxEnabled,
    SetLayerFxBlendMode,
    SetLayerFxStrokePosition,
    SetGaussianBlurRepeatEdge,
    SetStyleBlendMode,
    SetLayerBlendMode,
    SetStrokePosition,
    AddMask,
    RemoveMask,
    MoveMask,
    SetMaskMode,
    SetMaskInverted,
    SetTrackMatte,
    ConvertGeometryToPath,
    SetSpatialTangents,
    SetFollowPath,
    SetTextPath,
    ImportImageAsset,
    SetImageAsset,
    SetImageScaleMode,
    SetTextBoxTextMode,
    SetTextAlign,
    SetTextFont,
    SetTextFontSize,
    SetTextSize,
    AddShader,
    RemoveShader,
    UpdateShaderDefinition,
    SetStylePaintMode,
    SetGradientType,
    AddGradientStop,
    RemoveGradientStop,
    Composite,
};

}  // namespace motion
